databases:
  - name: Byosha_DB
    databaseName: byosha_db
    user: Byosha
    region: singapore

services:
  - type: web
    name: Byosha
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Byosha_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

